CREATE TABLE IF NOT EXISTS NOBLE_WIN(
    YEAR INTEGER,
    SUBJECT TEXT,
    WINNER TEXT,
    COUNTRY TEXT,
    CATEGORY TEXT
);

INSERT INTO NOBLE_WIN(YEAR, SUBJECT, WINNER, COUNTRY, CATEGORY) VALUES 
    (1970, 'PHYSICS', 'HANNES ALFVEN', 'SWEDEN', 'SCIENTIST'),
    (1970, 'PHYSICS', 'LOUIS NEEL', 'FRANCE', 'SCIENTIST'),
    (1971, 'PHYSICS', 'PAUL', 'FRANCE', 'SCIENTIST')
    (1972, 'CHEMISTRY', 'HAMILTON', 'SWEDEN', 'LINGUIST')
    (1972, 'LITREATURE', 'BERNARD KELSON', 'GERMANY', 'ECONIMIST')
    (1972, 'ECONIMICS', 'JOSEPH', 'RUSSIA', 'ECONIMIST')
    (1973, 'BIOLOGY', 'PHILIPS', 'USA', 'PRIME MINISTER')
    (1980, 'BIOLOGY', 'MARTIN', 'USA', 'PRESIDENT')
    (1981, 'PHYSIOLOGY', 'HANNAH', 'HUNGARY', 'SCIENTIST')
    (1975)